export const IS_REQUESTING = "IS_REQUESTING";
export type IS_REQUESTING_TYPE = typeof IS_REQUESTING;

export const IS_REQUESTING_COMPLETED = "IS_REQUESTING_COMPLETED";
export type IS_REQUESTING_COMPLETED_TYPE = typeof IS_REQUESTING_COMPLETED;

export const RAISE_ERROR_MESSAGES = "RAISE_ERROR_MESSAGES";
export type RAISE_ERROR_MESSAGES_TYPE = typeof RAISE_ERROR_MESSAGES;

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export type CHANGE_LANGUAGE_TYPE = typeof CHANGE_LANGUAGE;
